---
- hosts: all
  become: true
  tasks:
    - block:
        - name: Copy file to remote
          copy:
            src: uninstall_ubuntu_package.sh
            dest: /tmp/uninstall_packages.sh
            mode: 0777
        - name: Run script
          shell: bash /tmp/uninstall_packages.sh
      when: ansible_distribution|lower == 'ubuntu'

    - block:
        - name: Copy file to remote
          copy:
            src: uninstall_debian.sh
            dest: /tmp/uninstall_packages.sh
            mode: 0777
        - name: Run script
          shell: bash /tmp/uninstall_packages.sh
      when: ansible_distribution|lower == 'debian'
...